name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      -name: Checkout
       uses: actions/checkout@v2

      -name: Add remote
       run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/hrga.git

      -name: Push to heroku
       run: git push heroku main  
